const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const app = $('#main');
const live = $('#live');
const state = { name:'', screen:0, completed:0, goal:'', reflection:'', tts:null, start:{}, join:{timing:false}, end:[], finalStage:0, typeToken:0, typeTimers:[] };

const A='assets/ui/';
const icons={
  greet:A+'icon-greet.jpeg', open:A+'icon-open.jpeg', notice:A+'icon-notice.jpeg', listen:A+'icon-listen.jpeg', wait:A+'icon-wait.jpeg', connect:A+'icon-connect.jpeg', signal:A+'icon-signal.jpeg', finish:A+'icon-finish.jpeg', exit:A+'icon-exit.jpeg'
};
const strips={start:A+'start-strip.png',join:A+'join-strip.png',end:A+'end-strip.png',combined:A+'combined-strip.png'};

const adultInfo={
about:`<h3>What is the Conversation Mission?</h3><p><strong>GLORB // Conversation Mission</strong> is an interactive explicit-teaching lesson that breaks conversation into three teachable areas: <strong>START, JOIN and END</strong>.</p><p>Students practise selected strategies involved in beginning an interaction, joining one already underway and ending an interaction clearly.</p><div class="protocol"><div><strong>START</strong> · construct an opener</div><div><strong>JOIN</strong> · notice conversational timing and choose a topic-connected response</div><div><strong>END</strong> · sequence a conversational ending</div></div><h3>This resource is a teaching aid</h3><p>The Conversation Mission is designed to make selected conversation strategies visible, explicit and easier to practise. It does not reproduce everything that happens in a natural conversation.</p>`,
learning:`<h3>What students learn</h3><div class="teaching-list"><div class="teaching-item"><strong>START · GREET → OPEN → NOTICE</strong><p>Greet another person, use a simple opening question or comment, then pause to notice the person's response.</p></div><div class="teaching-item"><strong>JOIN · LISTEN → WAIT → CONNECT</strong><p>Identify the current topic, wait for conversational space, then add something connected to what is already being discussed.</p></div><div class="teaching-item"><strong>END · SIGNAL → FINISH PHRASE → EXIT</strong><p>Give a clue that you are preparing to leave, use language that makes the ending clear, then leave the interaction.</p></div></div><h3>How it teaches</h3><p>Each mission follows a repeated learning cycle: <strong>story problem → explicit teaching → put it together → model → practise → explanatory feedback → review.</strong></p>`,
curriculum:`<h3>Australian Curriculum Version 9.0</h3><p><strong>Personal and Social Capability · Social Management → Communication</strong></p><p>The strongest Years 5–6 connection identified in the academic report is Communication Level 4: <q>apply skills to address factors that influence verbal and non-verbal communication</q>.</p><p>The Mission addresses timing, conversational availability, topic relevance, entry into interaction, response to others and closure.</p><p><strong>Supporting connection: Collaboration.</strong> Joining and contributing can support participation with others, but the Mission does not teach the fuller Years 5–6 group-coordination descriptor.</p>`,
evidence:`<h3>Evidence-informed design</h3><div class="teaching-list"><div class="teaching-item"><strong>Skillstreaming lineage</strong><p>Beginning a Conversation, Joining In and Ending a Conversation provide the most direct behavioural lineage.</p></div><div class="teaching-item"><strong>Explicit teaching</strong><p>The strategy is taught before the learner is asked to demonstrate it.</p></div><div class="teaching-item"><strong>Segmentation</strong><p>One major concept is presented at a time before the components are combined.</p></div><div class="teaching-item"><strong>Formative feedback</strong><p>Incorrect responses explain why a response does not fit and support another attempt.</p></div><div class="teaching-item"><strong>Active practice</strong><p>Students construct, wait, select and sequence rather than only read or recognise.</p></div><div class="teaching-item"><strong>Age-respectful design</strong><p>The learner is positioned as the Earth Expert helping Glorb understand unwritten rules.</p></div></div>`,
use:`<div class="notice-box"><h3>Important</h3><p><strong>The Conversation Mission is not a real-life conversation and completing it does not demonstrate independent conversational competence.</strong></p><p>It is an aid to explicit conversation teaching. It should be used, where possible, alongside in-person explanation, adult modelling, discussion, guided rehearsal, role-play, peer interaction, natural opportunities to practise and teacher observation.</p></div><h3>It is designed to help, not to be a complete solution</h3><p>Digital success shows supported performance inside this structured lesson. It does not prove that the learner will independently use the same strategy with peers, unfamiliar people, across environments or over time.</p><h3>This resource does not</h3><p>Diagnose a condition, measure overall social competence, determine whether a learner is “good” or “bad” at conversation, require one communication style in every context, represent every valid way a conversation can occur, prove real-world mastery, replace professional assessment, replace responsive in-person teaching, or guarantee generalisation.</p><h3>Conversation is contextual</h3><p>The strategies are useful options, not universal scripts. People communicate differently depending on culture, relationship, communication style, environment, language, familiarity, sensory needs and personal preference.</p>`,
references:`<h3>References used in the source-verified report</h3><div class="ref-list"><div>Afsharnejad, B., Whitehorne Smith, P., Bölte, S., Milbourn, B., & Girdler, S. (2026). A systematic review of implicit versus explicit social skills group programs.</div><div>Australian Curriculum, Assessment and Reporting Authority. (2022). Australian Curriculum: General capabilities – Personal and Social capability Version 9.0.</div><div>Carruthers, S., et al. (2020). Beyond intervention into daily life: generalisation following social communication interventions.</div><div>Cipriano, C., et al. (2023). The state of evidence for social and emotional learning.</div><div>Durlak, J. A., et al. (2011). The impact of enhancing students' social and emotional learning.</div><div>Gates, J. A., Kang, E., & Lerner, M. D. (2017). Efficacy of group social skills interventions for youth with autism spectrum disorder.</div><div>Mayer, R. E. (2017). Using multimedia for e-learning.</div><div>McGinnis, E. (2012). <em>Skillstreaming the Elementary School Child</em>.</div><div>Pearson, P. D., & Gallagher, M. C. (1983). The instruction of reading comprehension.</div><div>Powell, L., et al. (2024). Suitability and acceptability of co-designed psychoeducational content for autistic children.</div><div>Queensland Department of Education. (2021). Inclusive education policy.</div><div>Ramdoss, S., et al. (2012). Computer-based interventions to improve social and emotional skills in autism.</div><div>Research Press. Skillstreaming: A guide for teaching prosocial skills.</div><div>Rey, G. D., et al. (2019). A meta-analysis of the segmenting effect.</div><div>Ryan, R. M., & Deci, E. L. (2000). Self-determination theory.</div><div>Scarcella, I., et al. (2023). ICT-based interventions for children with autism spectrum conditions.</div><div>Shute, V. J. (2008). Focus on formative feedback.</div><div>Soares, E. E., et al. (2021). Social skills training for autism spectrum disorder.</div><div>Victorian Department of Education and Training. (2020). High impact teaching strategies.</div><div>Wang, Y., et al. (2024). Self-determination-theory-based interventions in education.</div><div>Wisniewski, B., Zierer, K., & Hattie, J. (2020). The power of feedback revisited.</div><div>Wolstencroft, J., et al. (2018). Group social skills interventions for children with high functioning autism spectrum disorder.</div></div>`
};

function asset(src,alt,cls=''){return `<div class="asset-card ${cls}"><img src="${src}" alt="${alt}"></div>`}
function actions(label='Continue', next=()=>go(state.screen+1), secondary=''){ setTimeout(()=>{ const b=$('#primaryAction'); if(b) b.onclick=next; if(secondary){const s=$('#secondaryAction'); if(s) s.onclick=secondary;} },0); return `<div class="actions"><button id="primaryAction" class="primary" type="button">${label}</button>${secondary?'<button id="secondaryAction" class="ghost" type="button">Back</button>':''}</div>` }
function frame({eyebrow='',title='',body='',visual='',act='',className=''}){return `<section class="screen ${className}" data-readable><div class="${visual?'hero-grid':''}"><div><div class="eyebrow">${eyebrow}</div><h1 tabindex="-1">${title}</h1>${body}${act}</div>${visual||''}</div></section>`}
function glorb(text){return `<div class="glorb-line"><span class="eyebrow">GLORB</span><p class="glorb-quote type-line">“${text}”</p></div>`}
function rule(text){return `<div class="key-rule"><span class="type-line">${text}</span></div>`}
function go(n){ stopSpeech(); state.screen=n; render(); window.scrollTo(0,0); }
function setProgress(label,count,ratio){$('#progressLabel').textContent=label;$('#progressCount').textContent=count;$('#progressFill').style.width=`${ratio}%`;}
function announce(msg){live.textContent='';setTimeout(()=>live.textContent=msg,20)}
function focusHeading(){setTimeout(()=>{const h=$('h1',app); if(h) h.focus({preventScroll:true})},20)}
function screenHelp(){ const s=state.screen; if(s>=3&&s<=10)return '<p><strong>START:</strong> Greet → Open → Notice.</p><p>Look for the choice that makes the rule visible, not the most dramatic option.</p>';if(s>=11&&s<=19)return '<p><strong>JOIN:</strong> Listen → Wait → Connect.</p><p>Think about two things: <strong>Topic + Space.</strong></p>';if(s>=20&&s<=27)return '<p><strong>END:</strong> Signal → Finish Phrase → Exit.</p><p>Give a clue before leaving.</p>';return '<p>Move at your own pace. Use Read aloud whenever it helps. There is no penalty for using a clue or trying again.</p>'; }

function render(){
  if(state.screen<=2)setProgress('ORIENTATION',`${state.completed} / 3 missions complete`,0);
  else if(state.screen<=10)setProgress('MISSION 01 // START',`${state.completed} / 3 missions complete`,33*(state.completed));
  else if(state.screen<=19)setProgress('MISSION 02 // JOIN',`${state.completed} / 3 missions complete`,33*(state.completed));
  else if(state.screen<=27)setProgress('MISSION 03 // END',`${state.completed} / 3 missions complete`,33*(state.completed));
  else setProgress('FINAL INTEGRATION',`${state.completed} / 3 missions complete`,100);
  clearTypewriters();
  const fn=screens[state.screen]||screens[0];
  app.innerHTML=fn();
  bindDynamic();
  applyTypewriter();
  focusHeading();
}

const screens=[
()=>frame({eyebrow:'EARTH EXPERT REGISTRATION',title:"Hi, I'm Glorb.",body:`<p class="lead">I'm visiting Earth from <strong>Planet Zorbax-9</strong>. I've come here to study how humans behave.</p><p class="lead">There is one problem. <strong>Human conversations are confusing.</strong></p><p class="lead">I need your help.</p><div class="name-field"><label for="learnerName">Enter your name</label><input id="learnerName" autocomplete="given-name" maxlength="30" placeholder="First name or initials"><div class="helper">This helps Glorb know what to call you and personalises your certificate. Your name is kept only in this page session.</div></div>`,visual:asset(A+'glorb-full.png','Black-and-white drawing of Glorb standing','icon'),act:actions('Begin mission',()=>{const v=$('#learnerName').value.trim();if(!v){announce('Enter your name before beginning.');$('#learnerName').focus();return;}state.name=v;go(1);})}),
()=>frame({eyebrow:'INCOMING TRANSMISSION',title:'Human conversation',body:`<p class="lead"><strong>From:</strong> Glorb</p>${glorb(`Excellent, ${state.name}. You appear qualified because you are currently a human.`)}<p class="copy">I have three conversation problems I need help solving.</p>`,visual:asset(A+'glorb-portrait.png','Portrait drawing of Glorb','icon'),act:actions('Show me the first problem')}),
()=>frame({eyebrow:'MISSION CONTROL',title:'Three problems. One Earth Expert.',body:`<p class="lead">We will solve each problem one at a time. First you will see what happened to Glorb. Then you will learn the strategy, watch an example and practise it yourself.</p>${glorb('Nobody announces the rules. This seems inefficient.')}`,act:actions('Start Mission 01')}),
()=>frame({eyebrow:'MISSION 01 // START · STORY',title:'This situation happened to me earlier.',body:`<p class="copy">I wanted to talk to Maya.</p><p class="copy">I walked over and said:</p>${rule('“HELLO. LET US BEGIN FRIENDSHIP.”')}<p class="copy">Maya looked confused.</p>${glorb('I thought this clearly communicated my objective.')}<p class="lead"><strong>How can I start a conversation in a way that gives Maya something easy to respond to?</strong></p>`,visual:asset(A+'story-start.png','Glorb greeting Maya by saying Hello. Let us begin friendship.'),act:actions('Learn the START protocol')}),
()=>teachScreen('MISSION 01 // START','Step 1 // GREET',icons.greet,'Hand-drawn GREET icon',`<p class="lead">Start by letting the person know you are talking to them.</p><div class="teaching-list"><div class="teaching-item"><strong>You can:</strong><br>say hello<br>use their name if you know it</div><div class="teaching-item"><strong>Example:</strong><br>“Hi Maya.”</div></div><p class="copy">I did say hello, but I added a very strong statement immediately afterwards. A simple greeting is enough to begin.</p>${glorb('Apparently friendship does not require an immediate official announcement.')}`,'Next step'),
()=>teachScreen('MISSION 01 // START','Step 2 // OPEN',icons.open,'Hand-drawn OPEN speech bubble icon',`<p class="lead">After greeting someone, give them something they can respond to.</p><div class="teaching-list"><div class="teaching-item"><strong>You can:</strong><br>ask a simple question<br>or make a comment</div><div class="teaching-item"><strong>Example:</strong><br>“How was your weekend?”</div></div>${rule('AN OPENER GIVES THE OTHER PERSON SOMETHING THEY CAN RESPOND TO.')}<p class="copy"><strong>Poor fit:</strong> “Tell me every fact about yourself.”<br>That asks for a lot at once.</p>${glorb('One manageable question. Not an interrogation. Recorded.')}`,'Next step'),
()=>teachScreen('MISSION 01 // START','Step 3 // NOTICE',icons.notice,'Hand-drawn NOTICE icon',`<p class="lead">After greeting and opening, <strong>pause</strong> and notice what the other person does next.</p><p class="copy">They might answer, ask something back, keep talking, give a short response, look busy, or show they do not want to continue.</p>${rule('STARTING A CONVERSATION DOES NOT MEAN YOU HAVE TO KEEP TALKING.')}<p class="copy">Give the other person space to respond.</p>${glorb('This requires surprisingly little uninterrupted speaking.')}`,'Put it together'),
()=>frame({eyebrow:'MISSION 01 // START',title:'Put the START protocol together',body:`${asset(strips.start,'Greet, Open, Notice visual sequence')}<div class="protocol-steps"><div class="step-card"><strong>GREET</strong>Let them know you are talking to them.</div><div class="step-card"><strong>OPEN</strong>Give them something simple to respond to.</div><div class="step-card"><strong>NOTICE</strong>Pause and see what happens next.</div></div>${rule('A USEFUL START GIVES BOTH PEOPLE A WAY INTO THE CONVERSATION.')}`,act:actions('Watch Glorb try')}),
()=>frame({eyebrow:'MISSION 01 // START · MODEL',title:'Watch Glorb try',body:`<div class="conversation"><div class="bubble"><div class="speaker">GLORB</div>Hi Maya. How was your weekend?</div><div class="bubble right"><div class="speaker">MAYA</div>Good! We went to the beach.</div></div><div class="teaching-list"><div class="teaching-item"><strong>GREET ✓</strong><br>“Hi Maya.”</div><div class="teaching-item"><strong>OPEN ✓</strong><br>“How was your weekend?”</div><div class="teaching-item"><strong>NOTICE ✓</strong><br>Glorb pauses and listens.</div></div>${rule('GLORB GAVE MAYA SOMETHING EASY TO RESPOND TO.')}${glorb('Interesting. Less dramatic. More effective.')}`,act:actions('My turn')}),
()=>startAssessment(),
()=>completeScreen('START','GREET ✓ → OPEN ✓ → NOTICE ✓','Glorb greeted Maya, gave her something to respond to, and paused to notice what happened next.','Conversation initiated. No emergency evacuation detected.','Next mission',()=>{state.completed=Math.max(state.completed,1);go(11)}),
()=>frame({eyebrow:'MISSION 02 // JOIN · STORY',title:'This situation happened to me earlier.',body:`<p class="copy">Another human told me:</p>${rule('“Finding something you have in common can help you connect with people.”')}<p class="copy">Later, I saw Maya and Milo talking about handball.</p><p class="copy">I thought: <strong>“Handball involves feet. I also possess feet.”</strong></p><p class="copy">So I announced:</p>${rule('“I ALSO POSSESS FEET.”')}<p class="copy">They looked confused.</p>${glorb('The statement was factually accurate. I remain confused.')}<p class="lead"><strong>How can I join a conversation that is already happening?</strong></p>`,visual:asset(A+'story-join.png','Glorb telling two surprised students I also possess feet.'),act:actions('Learn the JOIN protocol')}),
()=>teachScreen('MISSION 02 // JOIN','Step 1 // LISTEN',icons.listen,'Hand-drawn LISTEN ear icon',`<p class="lead">Before joining, work out what people are talking about.</p>${rule('LISTEN FOR THE CURRENT TOPIC.')}<p class="copy">Maya and Milo are talking about <strong>this handball game</strong>, not simply sports, feet, playgrounds or things involving balls.</p><p class="copy">A word can remind you of something without that thing being the current topic.</p>${glorb('So the category is not necessarily the conversation.')}`,'Next step'),
()=>teachScreen('MISSION 02 // JOIN','Step 2 // WAIT',icons.wait,'Hand-drawn WAIT clock icon',`<p class="lead">When people are already speaking, look or listen for a space before you join.</p><div class="conversation"><div class="bubble">MAYA TALKING</div><div class="bubble right">MILO TALKING</div><div class="pause-card">PAUSE</div></div>${rule('WAIT FOR A SPACE, NOT A MAGIC NUMBER OF SECONDS.')}<p class="copy">You are listening for someone finishing their turn or a natural pause.</p>${glorb('Excellent. I was concerned a stopwatch would be required.')}`,'Next step'),
()=>teachScreen('MISSION 02 // JOIN','Step 3 // CONNECT',icons.connect,'Hand-drawn CONNECT puzzle icon',`<p class="lead">When you join, say something connected to what people are discussing <strong>right now</strong>.</p><div class="topic-map"><div class="topic-good"><strong>CURRENT TOPIC: HANDBALL GAME</strong><br>last round<br>ball was out<br>next round<br>who won</div><div class="topic-off"><strong>RELATED, BUT NOT THE CURRENT TOPIC</strong><br>soccer yesterday<br>feet</div></div>${rule('RELATED DOES NOT ALWAYS MEAN CONNECTED TO THE CURRENT TOPIC.')}<p class="copy">Soccer and handball are both sports. But Maya and Milo are talking about this handball game.</p>${glorb('So technically related is not always conversation related.')}`,'Put it together'),
()=>frame({eyebrow:'MISSION 02 // JOIN',title:'Put the JOIN protocol together',body:`${asset(strips.join,'Listen, Wait, Connect visual sequence')}<div class="protocol-steps"><div class="step-card"><strong>LISTEN</strong>What are they talking about?</div><div class="step-card"><strong>WAIT</strong>Is there a space?</div><div class="step-card"><strong>CONNECT</strong>What can I add that fits?</div></div>${rule('TOPIC + SPACE')}`,act:actions('Watch Glorb try')}),
()=>frame({eyebrow:'MISSION 02 // JOIN · MODEL',title:'Watch Glorb try',body:`<div class="conversation"><div class="bubble"><div class="speaker">MAYA</div>The last round was so close.</div><div class="bubble right"><div class="speaker">MILO</div>I thought the ball was out!</div><div class="pause-card">PAUSE</div><div class="bubble"><div class="speaker">GLORB</div>That game sounded close. Can I join the next round?</div></div><div class="teaching-list"><div class="teaching-item"><strong>LISTEN ✓</strong> Glorb identified the topic.</div><div class="teaching-item"><strong>WAIT ✓</strong> Glorb waited for a space.</div><div class="teaching-item"><strong>CONNECT ✓</strong> Glorb added something about the handball game.</div></div>${rule('GLORB NOTICED BOTH THE TOPIC AND THE SPACE.')}${glorb('Two variables. This is becoming unnecessarily sophisticated.')}`,act:actions('My turn')}),
()=>joinTimingAssessment(),
()=>joinTopicAssessment(),
()=>completeScreen('JOIN','LISTEN ✓ → WAIT ✓ → CONNECT ✓','Glorb listened for the topic, waited for space, and added something connected.','I entered the conversation without causing system shutdown.','Next mission',()=>{state.completed=Math.max(state.completed,2);go(20)}),
()=>frame({eyebrow:'MISSION 03 // END · STORY',title:'This situation happened to me earlier.',body:`<p class="copy">I finally had a good conversation. I greeted Maya. I listened. I stayed on topic.</p><p class="copy">Then I decided I was finished.</p>${rule('SO I RAN AWAY.')}<p class="copy">Later, another human told me: <strong>“You need to let people know when the conversation is finished.”</strong></p>${glorb('I had finished. I assumed leaving at maximum speed communicated this.')}<p class="lead"><strong>How can I show that I am ready to end the conversation?</strong></p>`,visual:asset(A+'story-end.png','Glorb running away quickly while two students look confused.'),act:actions('Learn the END protocol')}),
()=>teachScreen('MISSION 03 // END','Step 1 // SIGNAL',icons.signal,'Hand-drawn SIGNAL flag icon',`<p class="lead">Give the other person a clue that you are getting ready to leave.</p><div class="teaching-list"><div class="teaching-item">“The bell is about to ring.”</div><div class="teaching-item">“I need to get back to class.”</div><div class="teaching-item">“I have to go soon.”</div></div>${rule('A SIGNAL MAKES THE ENDING LESS SUDDEN.')}${glorb('So the escape begins before the actual escape.')}`,'Next step'),
()=>teachScreen('MISSION 03 // END','Step 2 // FINISH PHRASE',icons.finish,'Hand-drawn FINISH PHRASE speech bubble icon',`<p class="lead">Use words that clearly show the conversation is finishing.</p><div class="teaching-list"><div class="teaching-item">“I have to go, but it was good talking.”</div><div class="teaching-item">“Thanks for talking with me.”</div><div class="teaching-item">“I'll see you later.”</div></div>${rule('A FINISH PHRASE MAKES THE ENDING CLEAR.')}${glorb('A verbal closing procedure. Efficient.')}`,'Next step'),
()=>teachScreen('MISSION 03 // END','Step 3 // EXIT',icons.exit,'Hand-drawn EXIT or wave icon',`<p class="lead">After you have made the ending clear, leave the conversation.</p><p class="copy">You might walk away, wave, return to class or move to another activity.</p>${rule('EXIT COMES AFTER THE ENDING HAS BEEN MADE CLEAR.')}${glorb('This explains the problem with my sprinting method.')}`,'Put it together'),
()=>frame({eyebrow:'MISSION 03 // END',title:'Put the END protocol together',body:`<div class="protocol"><div class="protocol-steps"><div class="step-card"><strong>SIGNAL</strong>Give a clue.</div><div class="step-card"><strong>FINISH PHRASE</strong>Finish with words.</div><div class="step-card"><strong>EXIT</strong>Then leave.</div></div></div>${rule('GIVE A CLUE → FINISH WITH WORDS → THEN GO.')}`,visual:asset(strips.combined,'Combined hand-drawn START, JOIN and END strategy visual'),act:actions('Watch Glorb try')}),
()=>frame({eyebrow:'MISSION 03 // END · MODEL',title:'Watch Glorb try',body:`<div class="conversation"><div class="bubble"><div class="speaker">GLORB · SIGNAL ✓</div>The bell is about to ring.</div><div class="bubble"><div class="speaker">GLORB · FINISH PHRASE ✓</div>I have to go, but it was good talking.</div><div class="bubble"><div class="speaker">GLORB · EXIT ✓</div>See you at lunch!</div></div><p class="copy">Glorb waves and leaves.</p>${glorb('This appears more informative than suddenly disappearing.')}`,act:actions('My turn')}),
()=>endAssessment(),
()=>completeScreen('END','SIGNAL ✓ → FINISH PHRASE ✓ → EXIT ✓','Glorb gave a clue, used a finish phrase, and then left.','No unexplained disappearance required.','Continue',()=>{state.completed=3;go(28)}),
()=>frame({eyebrow:'FINAL INTEGRATION',title:'A conversation can have different parts',body:`${asset(strips.combined,'Combined hand-drawn strategy map for Start, Join and End')}<div class="teaching-list"><div class="teaching-item"><strong>START</strong><br>GREET → OPEN → NOTICE</div><div class="teaching-item"><strong>JOIN</strong><br>LISTEN → WAIT → CONNECT</div><div class="teaching-item"><strong>END</strong><br>SIGNAL → FINISH PHRASE → EXIT</div></div><p class="copy">You will not always use every step in exactly the same way. Real conversations change depending on the people and situation. These strategies give Glorb a useful place to start.</p>${glorb('I now possess nine conversation-related procedures.')}`,act:actions('Run final mission')}),
()=>finalMission(),
()=>frame({eyebrow:'FINAL MISSION COMPLETE',title:'You helped Glorb use the three protocols together.',body:`${asset(strips.combined,'Start, Join and End combined visual')}<div class="teaching-list"><div class="teaching-item"><strong>START ✓</strong> Greet → Open → Notice</div><div class="teaching-item"><strong>JOIN ✓</strong> Listen → Wait → Connect</div><div class="teaching-item"><strong>END ✓</strong> Signal → Finish Phrase → Exit</div></div><p class="lead">You practised each protocol separately and then used them together in one supported Conversation Mission.</p>`,act:actions('Quick review')}),
()=>retrieval(),
()=>transfer(),
()=>reflection(),
()=>frame({eyebrow:'TRANSMISSION FROM GLORB',title:`Dear ${state.name},`,body:`<p class="lead">It worked.</p><p class="copy">I learned how to <strong>start a conversation</strong>, <strong>join a conversation already happening</strong>, and <strong>let humans know before I disappear</strong>.</p><p class="copy">I greeted Maya, gave her something she could respond to and noticed what happened next.</p><p class="copy">I listened to what Maya and Milo were discussing, waited for a space and joined their topic.</p><p class="copy">When I needed to leave, I gave them a clue, used a finish phrase and then exited.</p>${rule('EARTH CONVERSATIONS REMAIN UNNECESSARILY COMPLICATED, BUT I NOW POSSESS A WORKING PROTOCOL.')}<p class="copy">Thank you, Earth Expert.</p><p><strong>GLORB</strong><br>Chief Curiosity Officer<br>Planet Zorbax-9</p>`,visual:asset(A+'glorb-portrait.png','Portrait drawing of Glorb','icon'),act:actions('View certificate')}),
()=>certificate()
];

function teachScreen(eyebrow,title,img,alt,body,label){return frame({eyebrow,title,body,visual:asset(img,alt,'icon'),act:actions(label)})}
function completeScreen(kind,seq,summary,joke,label,next){return `<section class="screen"><div class="mission-complete"><div class="eyebrow">MISSION COMPLETE</div><h1 tabindex="-1">${kind} protocol complete</h1><div class="key-rule" style="color:var(--ink)">${seq}</div><p class="lead">${summary}</p>${glorb(joke)}${actions(label,next)}</div></section>`}

function startAssessment(){
 const groups=[
  {key:'greet',label:'STEP 1 // GREET',correct:'Hi, Maya!',opts:[['Hi, Maya!',true,'This works because it is a simple greeting that clearly starts the interaction.'],['HELLO. LET US BEGIN FRIENDSHIP.',false,'That tells Maya what Glorb wants, but it is much stronger than a usual greeting. A simple hello gives the conversation somewhere to begin. Look for a short greeting.'],['Say nothing and stare.',false,'Maya does not know that Glorb wants to start a conversation. A greeting gives the other person a clear signal that you are beginning. Look for the option where Glorb says hello.']]},
  {key:'open',label:'STEP 2 // OPEN',correct:'How was your weekend?',opts:[['How was your weekend?',true,'This works because Maya has one simple question she can respond to.'],['Tell me every fact about yourself.',false,'That asks Maya to give Glorb a lot of information all at once. A simple question is usually easier to answer and can help the conversation begin. Look for a question that Maya can answer easily.'],['Begin a long story about Zorbax-9.',false,'Glorb is beginning with his own topic before giving Maya a chance to respond. A useful opener gives the other person something they can answer or comment on.']]},
  {key:'notice',label:'STEP 3 // NOTICE',correct:'Pause and notice Maya’s response.',opts:[['Pause and notice Maya’s response.',true,'This works because Glorb gives Maya space to respond and notices what happens next.'],['Keep talking without pausing.',false,'If Glorb keeps talking, Maya does not get a turn. After opening a conversation, pause and notice what the other person does next.'],['Walk away immediately.',false,'Glorb has started the conversation, but leaving immediately does not give Maya a chance to respond. Pause and notice what happens next.']]}
 ];
 let html=`<section class="screen" data-readable><div class="eyebrow">MISSION 01 // START · PRACTISE</div><h1 tabindex="-1">Build Glorb's opener</h1><p class="lead">Choose one part for each step.</p><div class="build-grid">`;
 groups.forEach(g=>{html+=`<div class="build-step"><h3>${g.label}</h3><div class="choices">${g.opts.map(([t])=>`<button class="choice" data-start-group="${g.key}" data-value="${esc(t)}">${t}</button>`).join('')}</div></div>`});
 html+=`</div><div class="preview"><strong>GLORB'S OPENER</strong><div id="pGreet">${state.start.greet||'Greet…'}</div><div id="pOpen">${state.start.open||'Open…'}</div><div id="pNotice">${state.start.notice||'Notice…'}</div></div><div id="startFeedback"></div><div class="actions"><button id="testStart" class="primary" ${Object.keys(state.start).length<3?'disabled':''}>Test opener</button></div></section>`;
 setTimeout(()=>{
  $$('[data-start-group]').forEach(btn=>btn.onclick=()=>{const k=btn.dataset.startGroup,v=unesc(btn.dataset.value);state.start[k]=v;$$(`[data-start-group="${k}"]`).forEach(b=>b.classList.toggle('selected',b===btn));$('#p'+cap(k)).textContent=v;$('#testStart').disabled=Object.keys(state.start).length<3;});
  $('#testStart').onclick=()=>{let all=true;groups.forEach(g=>{const chosen=state.start[g.key];const opt=g.opts.find(o=>o[0]===chosen);if(!opt||!opt[1]){all=false;const b=$$(`[data-start-group="${g.key}"]`).find(x=>unesc(x.dataset.value)===chosen);if(b){b.classList.remove('selected');b.classList.add('tried');b.disabled=true;b.innerHTML+=` <span class="status-tag">TRIED</span>`;} delete state.start[g.key];$('#p'+cap(g.key)).textContent=cap(g.key)+'…';$('#startFeedback').innerHTML=`<div class="feedback"><strong>Try another option.</strong><br>${opt?opt[2]:'Look back at the rule.'}</div>`;announce(opt?opt[2]:'Try another option.');}});if(all){$('#startFeedback').innerHTML=`<div class="feedback good"><strong>✓ FITS THIS SITUATION</strong><br>Glorb greeted Maya, used a simple opener and paused to notice her response.</div>${actions('Complete START',()=>go(10))}`;announce('This opener fits the situation.');}}
 },0);return html;
}

function joinTimingAssessment(){setTimeout(()=>{let phase=0;const next=()=>{phase++; if(phase===1){$('#jtalk').innerHTML='<div class="bubble right"><div class="speaker">MILO</div>I thought the ball was out!</div>';$('#joinNow').disabled=true;$('#phaseLabel').textContent='MILO IS TALKING';setTimeout(next,1800)} else {$('#jtalk').innerHTML='<div class="pause-card">PAUSE · THERE IS A SPACE IN THE CONVERSATION</div>';$('#joinNow').disabled=false;$('#phaseLabel').textContent='PAUSE';announce('Pause. There is a space in the conversation.');}};setTimeout(next,1800);$('#joinNow').onclick=()=>{state.join.timing=true;go(18)};$('#replay').onclick=()=>go(17);$('#transcript').onclick=()=>{alert('Maya: The last round was so close.\nMilo: I thought the ball was out.\nThen there is a pause.');};},0);return `<section class="screen" data-readable><div class="eyebrow">MISSION 02 // JOIN · PRACTISE</div><h1 tabindex="-1">Find the space</h1><p class="lead">When could Glorb join?</p><div class="conversation"><div id="jtalk" class="bubble"><div class="speaker">MAYA</div>The last round was so close.</div><div id="phaseLabel" class="pause-card">MAYA IS TALKING</div></div><div class="actions"><button id="joinNow" class="primary" disabled>JOIN NOW</button><button id="replay" class="ghost">Replay</button><button id="transcript" class="ghost">Show transcript</button></div><p class="helper">The button unlocks when the conversational turn ends. You are not learning to count a set number of seconds.</p></section>`}

function joinTopicAssessment(){const opts=[['That game sounded close! Can I join the next round?',true,'This works because Glorb waited for the conversational space and added something about the handball game Maya and Milo were already discussing.'],['I played soccer yesterday.',false,'Soccer and handball are both sports, but Maya and Milo are talking about this handball game. Joining works better when Glorb connects to the topic they are discussing right now.'],['I ALSO POSSESS FEET.',false,'Glorb heard something connected to handball and thought having feet was something they had in common. But Maya and Milo are talking about the game, not about having body parts. Look for something connected to what they are actually discussing.'],['Stop talking. I have a better story.',false,'This takes over the conversation instead of joining it. Glorb needs to connect to what Maya and Milo are already talking about. Look for an answer that stays with their topic.']];setTimeout(()=>{$$('#joinChoices .choice').forEach(b=>b.onclick=()=>{const i=+b.dataset.i,o=opts[i];if(o[1]){b.classList.add('correct');b.innerHTML+=` <span class="status-tag">✓ FITS THIS SITUATION</span>`;$$('#joinChoices .choice').forEach(x=>x.disabled=true);$('#joinFeedback').innerHTML=`<div class="feedback good"><strong>✓ FITS THIS SITUATION</strong><br>${o[2]}</div>${actions('Complete JOIN',()=>go(19))}`;announce(o[2]);}else{b.classList.add('tried');b.disabled=true;b.innerHTML+=` <span class="status-tag">TRIED</span>`;$('#joinFeedback').innerHTML=`<div class="feedback"><strong>Try another option.</strong><br>${o[2]}</div>`;announce(o[2]);}})},0);return `<section class="screen" data-readable><div class="eyebrow">MISSION 02 // JOIN · PRACTISE</div><h1 tabindex="-1">Connect to the topic</h1><p class="lead">What could Glorb say now?</p><div class="key-rule">CURRENT TOPIC: THE HANDBALL GAME</div><div id="joinChoices" class="choices">${opts.map((o,i)=>`<button class="choice" data-i="${i}">${o[0]}</button>`).join('')}</div><div id="joinFeedback"></div></section>`}

function endAssessment(){const order=['SIGNAL','FINISH PHRASE','EXIT'];setTimeout(()=>bindEnd(),0);return `<section class="screen" data-readable><div class="eyebrow">MISSION 03 // END · PRACTISE</div><h1 tabindex="-1">Put the ending in order</h1><p id="endPrompt" class="lead">What comes first?</p><div id="endChoices" class="choices">${order.map((o,i)=>`<button class="choice" data-end="${o}">${o}</button>`).join('')}</div><div class="sequence"><div class="sequence-slot" id="slot0">1</div><div class="sequence-slot" id="slot1">2</div><div class="sequence-slot" id="slot2">3</div></div><div id="endFeedback"></div></section>`}
function bindEnd(){const order=['SIGNAL','FINISH PHRASE','EXIT'];$$('[data-end]').forEach(b=>b.onclick=()=>{const expected=order[state.end.length],val=b.dataset.end;if(val===expected){state.end.push(val);$('#slot'+(state.end.length-1)).textContent=`${state.end.length} · ${val}`;b.disabled=true;b.classList.add('correct');if(state.end.length===3){$('#endFeedback').innerHTML=`<div class="feedback good"><strong>✓ SEQUENCE COMPLETE</strong><br>Glorb signals, uses a finish phrase, then exits.</div>${actions('Complete END',()=>go(27))}`;$('#endPrompt').textContent='You built the ending.';}else{$('#endPrompt').textContent=state.end.length===1?'What comes next?':'What comes last?';}}else{b.classList.add('tried');b.disabled=true;b.innerHTML+=` <span class="status-tag">TRIED HERE</span>`;let msg=state.end.length===0&&val==='FINISH PHRASE'?'A finish phrase helps, but Maya and Milo still need a clue that Glorb is getting ready to leave. First, Glorb should signal that the conversation is ending.':state.end.length===0&&val==='EXIT'?'Leaving is the final step. If Glorb walks away first, Maya and Milo may not know the conversation has finished. Start by giving them a clue that he is getting ready to leave.':`That step comes later. Right now, look for ${expected}.`;$('#endFeedback').innerHTML=`<div class="feedback"><strong>Try another step.</strong><br>${msg}</div>`;announce(msg);}})}

function finalMission(){if(!state.finalStage)state.finalStage=1;setTimeout(()=>bindFinal(),0);let content='';if(state.finalStage===1)content=`<div class="eyebrow">PART 1 // START</div><h1 tabindex="-1">Glorb sees Maya.</h1><p class="lead">Which opener fits best?</p><div class="choices" id="finalChoices"><button class="choice" data-final="bad">HELLO. LET US BEGIN FRIENDSHIP.</button><button class="choice" data-final="good">Hi Maya. How did handball go?</button></div>`;if(state.finalStage===2)content=`<div class="eyebrow">PART 2 // JOIN</div><h1 tabindex="-1">Maya and Milo are talking.</h1><div class="conversation"><div class="bubble">The last round was so close.</div><div class="bubble right">I thought the ball was out.</div><div class="pause-card">PAUSE</div></div><p class="lead">What could Glorb add?</p><div class="choices" id="finalChoices"><button class="choice" data-final="bad">I played soccer yesterday.</button><button class="choice" data-final="good">That game sounded close. Can I join the next round?</button></div>`;if(state.finalStage===3)content=`<div class="eyebrow">PART 3 // END</div><h1 tabindex="-1">Glorb needs to leave.</h1><p class="lead">Which sequence makes the ending clear?</p><div class="choices" id="finalChoices"><button class="choice" data-final="bad">Run away → wave later → explain tomorrow</button><button class="choice" data-final="good">Signal → Finish Phrase → Exit</button></div>`;return `<section class="screen" data-readable>${content}<div id="finalFeedback"></div></section>`}
function bindFinal(){const c=$('#finalChoices');if(!c)return;$$('.choice',c).forEach(b=>b.onclick=()=>{if(b.dataset.final==='good'){b.classList.add('correct');b.disabled=true;const messages=['Glorb greets Maya and gives her something simple to respond to.','Glorb notices the space and connects to the current handball topic.','Glorb makes the ending clear before leaving.'];$('#finalFeedback').innerHTML=`<div class="feedback good"><strong>✓ FITS THIS SITUATION</strong><br>${messages[state.finalStage-1]}</div>${actions(state.finalStage<3?'Continue final mission':'Finish final mission',()=>{if(state.finalStage<3){state.finalStage++;render()}else go(30)})}`;}else{b.classList.add('tried');b.disabled=true;b.innerHTML+=` <span class="status-tag">TRIED</span>`;$('#finalFeedback').innerHTML='<div class="feedback">Try another option. Use the protocol you already practised.</div>';}})}

function retrieval(){const qs=[['GREET → ? → NOTICE','OPEN'],['LISTEN → ? → CONNECT','WAIT'],['SIGNAL → FINISH PHRASE → ?','EXIT'],['Before joining, what two things should Glorb notice?','TOPIC + SPACE']];setTimeout(()=>{let i=0;const show=()=>{const [q,a]=qs[i];$('#rq').textContent=q;$('#ra').value='';$('#rfeedback').innerHTML='';$('#checkR').onclick=()=>{if($('#ra').value.trim().toUpperCase()===a){$('#rfeedback').innerHTML='<div class="feedback good">✓ That matches the protocol.</div>';if(i<qs.length-1){$('#checkR').textContent='Next';$('#checkR').onclick=()=>{i++;$('#checkR').textContent='Check';show()}}else{$('#rfeedback').innerHTML+=actions('Choose a real-world goal',()=>go(32));}}else $('#rfeedback').innerHTML='<div class="feedback">Take another look at the protocol and try again. No points are lost.</div>';}};show();},0);return `<section class="screen" data-readable><div class="eyebrow">QUICK REVIEW</div><h1 tabindex="-1">What do you remember?</h1><p id="rq" class="lead"></p><div class="name-field"><label for="ra">Your answer</label><input id="ra" autocomplete="off"></div><div id="rfeedback"></div><div class="actions"><button id="checkR" class="primary">Check</button></div><p class="helper">This is low-stakes retrieval practice. There is no score.</p></section>`}

function transfer(){const choices=[['START','I will try one simple opening question or comment.'],['JOIN','I will listen for a pause before joining.'],['END','I will use a finish phrase before I leave.']];setTimeout(()=>{$$('.transfer-card').forEach(b=>b.onclick=()=>{state.goal=b.dataset.goal;$$('.transfer-card').forEach(x=>x.classList.toggle('selected',x===b));$('#continueGoal').disabled=false;});$('#continueGoal').onclick=()=>go(33)},0);return `<section class="screen" data-readable><div class="eyebrow">TRANSFER</div><h1 tabindex="-1">Take one skill off the screen</h1><p class="lead">You do not have to practise everything at once. Choose one small conversation strategy you would like to try again.</p><div class="transfer-grid">${choices.map(([h,t])=>`<button class="transfer-card" data-goal="${t}"><strong>${h}</strong><br>${t}</button>`).join('')}</div><div class="actions"><button id="continueGoal" class="primary" disabled>Continue</button></div></section>`}

function reflection(){const opts=['Seeing the examples','Practising it myself','Reading the steps','Listening to the instructions','Using a clue','Trying again after feedback',"I'm not sure yet"];setTimeout(()=>{$$('#reflectChoices .choice').forEach(b=>b.onclick=()=>{state.reflection=b.textContent;go(34)});$('#skipReflect').onclick=()=>go(34)},0);return `<section class="screen" data-readable><div class="eyebrow">OPTIONAL REFLECTION</div><h1 tabindex="-1">What helped you learn?</h1><p class="lead">There is no right answer.</p><div class="choices" id="reflectChoices">${opts.map(o=>`<button class="choice">${o}</button>`).join('')}</div><div class="actions"><button id="skipReflect" class="ghost">Skip reflection</button></div>${glorb("All data is useful. Even 'I am not sure yet.'")}</section>`}

function certificate(){setTimeout(()=>{$('#printCert').onclick=()=>window.print();$('#restart').onclick=()=>{clearTypewriters(); Object.assign(state,{name:'',screen:0,completed:0,goal:'',reflection:'',start:{},join:{timing:false},end:[],finalStage:0});render();}},0);return `<section class="screen"><article class="certificate" data-readable><div class="eyebrow" style="text-align:center">EARTH EXPERT CERTIFICATE</div><h1 tabindex="-1">GLORB'S CONVERSATION MISSION</h1><p style="text-align:center">THIS CERTIFIES THAT</p><div class="certificate-name">${esc(state.name)}</div><p class="lead" style="margin-inline:auto;text-align:center">During this lesson, ${esc(state.name)} helped Glorb learn and practise strategies for starting, joining and ending conversations.</p><p style="text-align:center">${esc(state.name)} practised each strategy separately and then used the three protocols together in the supported final Conversation Mission.</p><div class="cert-block"><h3>START · GREET → OPEN → NOTICE</h3><p>Greeting someone, using a simple question or comment to open a conversation, and pausing to notice the other person's response.</p></div><div class="cert-block"><h3>JOIN · LISTEN → WAIT → CONNECT</h3><p>Listening to what people are talking about, waiting for a space in the conversation, and adding something connected to the current topic.</p></div><div class="cert-block"><h3>END · SIGNAL → FINISH PHRASE → EXIT</h3><p>Giving a signal that the conversation is finishing, using a clear finish phrase, and then leaving.</p></div><div class="cert-block"><p><strong>${esc(state.name)} successfully completed the supported learning activities and practised applying these strategies within the Conversation Mission.</strong></p></div><div class="cert-block"><h3>MY NEXT EARTH MISSION</h3><p>${esc(state.goal||'Choose one conversation strategy to practise again.')}</p></div><div class="cert-footer">3 / 3 LEARNING MISSIONS COMPLETE · FINAL CONVERSATION MISSION COMPLETE · VERIFIED BY GLORB</div></article><div class="actions" style="justify-content:center"><button id="printCert" class="primary">Print / save certificate</button><button id="restart" class="ghost">Start over</button></div></section>`}

function bindDynamic(){
  $('#helpBtn').onclick=()=>{$('#helpContent').innerHTML=screenHelp();$('#helpDialog').showModal()};
  $('#infoBtn').onclick=()=>{showInfo('about');$('#infoDialog').showModal()};
  $$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
  $$('.tab').forEach(t=>t.onclick=()=>showInfo(t.dataset.tab));
  $('#readBtn').onclick=toggleSpeech;
  const textBtn=$('#textBtn'); if(textBtn) textBtn.onclick=finishTypewriters;
}
function showInfo(key){$$('.tab').forEach(t=>{const on=t.dataset.tab===key;t.classList.toggle('active',on);t.setAttribute('aria-selected',on)});$('#infoContent').innerHTML=adultInfo[key]}
function clearTypewriters(){
  state.typeToken++;
  state.typeTimers.forEach(clearTimeout);
  state.typeTimers=[];
}
function getScreenReadableText(){
  const node=$('[data-readable]',app)||app;
  return node.innerText.replace(/\s+/g,' ').trim();
}
function finishTypewriters(){
  clearTypewriters();
  $$('.screen [data-type-full]').forEach(el=>{
    const full=el.dataset.typeFull||'';
    if(full){
      const template=el._typeTemplate;
      if(template) el.innerHTML=template;
      else el.textContent=full;
    }
    el.classList.remove('typewriter-active');
    el.classList.add('typewriter-done');
  });
  const b=$('#textBtn');
  if(b)b.textContent='✓ Text shown';
}
function applyTypewriter(){
  state.screenReadableText=getScreenReadableText();
  const b=$('#textBtn');
  if(b)b.textContent='▣ Show text';
  const reduceMotion=window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  if(reduceMotion){
    if(b)b.textContent='✓ Text shown';
    return;
  }
  const nodes=$$('.screen .type-line, .screen p.lead, .screen p.copy, .screen p.helper')
    .filter(el=>el && !el.closest('.dialog') && el.textContent.trim());
  if(!nodes.length){
    if(b)b.textContent='✓ Text shown';
    return;
  }
  const token=++state.typeToken;
  let index=0;
  const next=()=>{
    if(token!==state.typeToken || index>=nodes.length){
      if(index>=nodes.length && b)b.textContent='✓ Text shown';
      return;
    }
    const el=nodes[index++];
    typeElementPreservingMarkup(el,token,next);
  };
  next();
}
function typeElementPreservingMarkup(el,token,onDone){
  if(token!==state.typeToken || !el.isConnected)return;
  const fullText=el.textContent.replace(/\s+/g,' ').trim();
  if(!fullText){onDone();return;}
  el.dataset.typeFull=fullText;
  el._typeTemplate=el.innerHTML;
  const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);
  const nodes=[];
  let node;
  while(node=walker.nextNode()){
    if(node.nodeValue && node.nodeValue.length)nodes.push({node,text:node.nodeValue});
  }
  nodes.forEach(x=>x.node.nodeValue='');
  el.classList.add('typewriter-active');
  el.classList.remove('typewriter-done');
  let ni=0, ci=0;
  const tick=()=>{
    if(token!==state.typeToken || !el.isConnected)return;
    if(ni>=nodes.length){
      el.classList.remove('typewriter-active');
      el.classList.add('typewriter-done');
      state.typeTimers.push(setTimeout(onDone,90));
      return;
    }
    const current=nodes[ni];
    ci++;
    current.node.nodeValue=current.text.slice(0,ci);
    if(ci>=current.text.length){ni++;ci=0;}
    const ch=current.text[Math.max(0,ci-1)]||'';
    const delay=/[.!?]/.test(ch)?70:/[,;:]/.test(ch)?45:ch===' '?9:18;
    state.typeTimers.push(setTimeout(tick,delay));
  };
  tick();
}
function readableText(){return state.screenReadableText||getScreenReadableText();}
function toggleSpeech(){if(!('speechSynthesis' in window)){announce('Read aloud is not available in this browser.');return;}if(speechSynthesis.speaking){stopSpeech();return;}const u=new SpeechSynthesisUtterance(readableText());u.lang='en-AU';u.rate=.96;u.onstart=()=>$('#readBtn').textContent='■ Stop';u.onend=()=>$('#readBtn').textContent='↻ Read again';u.onerror=()=>$('#readBtn').textContent='🔊 Read aloud';state.tts=u;speechSynthesis.speak(u)}
function stopSpeech(){if('speechSynthesis' in window)speechSynthesis.cancel();const b=$('#readBtn');if(b)b.textContent='🔊 Read aloud'}
function cap(s){return s.charAt(0).toUpperCase()+s.slice(1)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function unesc(s=''){const t=document.createElement('textarea');t.innerHTML=s;return t.value}

document.addEventListener('visibilitychange',()=>{if(document.hidden)stopSpeech()});
render();
